// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AtDialog: typeof import('./../src/components/AtDialog.vue')['default']
    Cropper: typeof import('./../src/components/cropper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExampleMarkdown: typeof import('./../src/components/exampleMarkdown.md')['default']
    GoBackHome: typeof import('./../src/components/GoBackHome.vue')['default']
    IconH1: typeof import('./../src/components/icons/iconH1.vue')['default']
    IconH2: typeof import('./../src/components/icons/iconH2.vue')['default']
    IconH3: typeof import('./../src/components/icons/iconH3.vue')['default']
    IconH4: typeof import('./../src/components/icons/iconH4.vue')['default']
    IconTable: typeof import('./../src/components/icons/iconTable.vue')['default']
    MyAutoComplete: typeof import('./../src/components/myAutoComplete.vue')['default']
    ParamsMenu: typeof import('./../src/components/paramsMenu.vue')['default']
    SandBox: typeof import('./../src/components/sandBox.vue')['default']
  }
}

export { }
